server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: item
          uri: http://localhost:8081
          predicates:
            - Path=/items/**, /chkAndModifyStock/** 
        - id: customercenter
          uri: http://localhost:8082
          predicates:
            - Path= /myPages/**
        - id: store
          uri: http://localhost:8083
          predicates:
            - Path=/stores/** 
        - id: reservation
          uri: http://localhost:8084
          predicates:
            - Path=/reservations/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: item
          uri: http://item:8080
          predicates:
            - Path=/items/**, /chkAndModifyStock/** 
        - id: customercenter
          uri: http://customercenter:8080
          predicates:
            - Path= /myPages/**
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/stores/** 
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080